apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ostad-app-ingress
  namespace: ostad-app
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ostad-app.rfft.nl
      secretName: ostad-app-cert
  rules:
    - host: "ostad-app.rfft.nl"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: ostad-app-service
                port:
                  number: 8000